name: Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23]
  
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure Node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        id: install-dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build