services:
  db:
    image: bitnami/postgresql:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - brev-ly
      - db

  migrate:
    image: node:23.11-alpine
    depends_on:
      - db
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - DATABASE_URL=$DATABASE_URL
    command: sh -c "npx wait-on tcp:db:5432 && npx drizzle-kit migrate"
    networks:
      - db

  app:
    build: .
    depends_on:
      - db
      - migrate
    container_name: brev-ly
    restart: unless-stopped
    ports:
      - 3000:$PORT
    environment:
      - PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - DATABASE_URL=$DATABASE_URL
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PORT=$POSTGRES_PORT
      - POSTGRES_DB=$POSTGRES_DB
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    networks:
      - brev-ly

volumes:
  db:
networks:
    brev-ly:
      driver: bridge
    db:
      driver: bridge